AllCops:
  Exclude:
    - 'README.md'
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 126 # Github fixed web line length
Metrics/ClassLength:
  Max: 500
Metrics/AbcSize:
  Max: 25
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/MethodLength:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 12
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/AlignHash:
  EnforcedColonStyle: table
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false # Default in ruby 3, so don't need to worry about, except we go some memory leaks
Layout/IndentationConsistency:
  EnforcedStyle: rails
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/PercentLiteralDelimiters:
  Enabled: false # Cause of a bug in codeclimate
Style/RegexpLiteral:
  Enabled: false
